name: Lorenzendelle
favicon: null
layout_spectrum: 0.45865651103667915
typography_spectrum: 0.49794786097481847
title: Lorenzendelle
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0
  lightness: 0.05194020248018205
  saturation: 0.49077688879333436
  rhythmicContrast: 0.5691248239018023
purpose: []
